export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL'; 
export const ADD_USERS = 'ADD_USERS';
export const DELETE_USERS = 'DELETE_USERS';
export const GET_SINGLE_USERS = 'GET_SINGLE_USERS';